server:
    port: 8080
spring:
    application:
        name: foo
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        password: 321
        username: postgres
    jpa:
        hibernate:
            #ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                #ddl-auto: create
        show-sql: true
        generate-ddl: true